apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: freedomforge-earth

resources:
  - crds/freedomforge-agent.yaml
  - operators/guardian-operator.yaml
  - argocd/application-freedomforge.yaml
  - istio/base/istio-install.yaml
  - istio/mesh/gateway.yaml
  - istio/mesh/virtualservice-bci.yaml
  - istio/mesh/destinationrule-mtls.yaml
  - istio/mesh/peerauthentication-spiffe.yaml
