#!/bin/bash
# Quick integration script for Agent Command Fix components
# ════════════════════════════════════════════════════════════════════════════

echo "✓ FreedomForge Agent Command Fix Components Ready"
echo ""
echo "Two new components created:"
echo "  1. AgentCommandPanel.tsx    — Improved agent UI with error handling"
echo "  2. AgentDiagnosticPanel.tsx — Self-diagnostic tool"
echo ""
echo "Integration options:"
echo ""
echo "━━━ Quick Integration (Recommended) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option A: Replace existing agent panel (if you have one)"
echo "  import AgentCommandPanel from '@/app/components/AgentCommandPanel';"
echo ""
echo "Option B: Add diagnostic page"
echo "  1. Create: app/diagnose/page.tsx"
echo "  2. Paste the code from docs/AGENT-COMMAND-FIX.md 'Option 3'"
echo "  3. Visit: http://localhost:3000/diagnose"
echo ""
echo "Option C: Add to dashboard sidebar"
echo "  import AgentDiagnosticPanel from '@/app/components/AgentDiagnosticPanel';"
echo "  <AgentDiagnosticPanel />"
echo ""
echo "━━━ Verification Steps ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Start dev server:"
echo "   npm run dev"
echo ""
echo "2. Log in at:"
echo "   http://localhost:3000/login"
echo ""
echo "3. Test agent command:"
echo "   fetch('/api/chat', {"
echo "     method: 'POST',"
echo "     headers: { 'Content-Type': 'application/json' },"
echo "     credentials: 'include',"
echo "     body: JSON.stringify({ message: 'hello' })"
echo "   }).then(r => r.json()).then(d => console.log(d))"
echo ""
echo "4. Check environment:"
echo "   grep OPENROUTER_API_KEY .env.local"
echo ""
echo "━━━ Troubleshooting ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If you get 'Unable to generate response':"
echo ""
echo "1. Check API keys:"
echo "   cat .env.local | grep -i key"
echo ""
echo "2. Check authentication:"
echo "   curl -b 'ff_session=<cookie>' http://localhost:3000/api/auth/session"
echo ""
echo "3. Check server:"
echo "   curl http://localhost:3000/api/health"
echo ""
echo "4. Check chat endpoint:"
echo "   curl -X POST http://localhost:3000/api/chat \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -b 'ff_session=<cookie>' \\"
echo "     -d '{\"message\":\"hello\"}'"
echo ""
echo "━━━ Documentation ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Full guide: docs/AGENT-COMMAND-FIX.md"
echo ""
echo "Contains:"
echo "  ✓ Root cause analysis"
echo "  ✓ Step-by-step solutions"
echo "  ✓ Integration examples"
echo "  ✓ Debugging guide"
echo "  ✓ Error response examples"
echo "  ✓ Required environment variables"
echo ""
